Try number two
DanilVolkov/lab-for-MO pull request #19
Opened 2024-04-16 11:05 UTC by StatsenkoArs

2024-04-16 12:36 UTC, ActiWait commented on method/nelder_mead.py
> +    while not np.isclose(simp, simp[0]).all():
just unreal!!!

2024-04-16 12:56 UTC, DanilVolkov requested changes

2024-04-16 12:56 UTC, DanilVolkov commented on method/func_parser.py
> +
У каждого своя задача, не нужно писать комментарии что кому сделать, тем более такие!

2024-04-16 12:56 UTC, DanilVolkov commented on tests/unit_tests.py
> +    def test_zeros(self):
В одном месте есть отступ от другой функции, в другом нет

2024-04-16 12:56 UTC, DanilVolkov commented on tests/unit_tests.py
> +        n = 2
Что такое n? Перед тем, как дать имя переменной, функции или классу, нужно ответить на вопросы:
Почему эта переменная (функция, класс и т.п.) существует?
Что она делает? (или какие данные в ней хранятся?)
Как используется?

Плохо: d
Хорошо: area

2024-04-16 12:56 UTC, DanilVolkov commented on tests/unit_tests.py
> +        f = lambda x: eval(func)
Также, нужно переименовать. Например func_parse

2024-04-16 12:56 UTC, DanilVolkov commented on method/nelder_mead.py
> +def calculate_neldermead(fun, n, alpha=1.5, beta=1.5, gamma=1.5):
Непонятно, что такое n

2024-04-16 12:56 UTC, DanilVolkov commented on method/nelder_mead.py
> +    simp = np.eye(n + 1, n)
simp - это что?

2024-04-16 12:56 UTC, DanilVolkov commented on method/nelder_mead.py
> +        fun_val = [fun(x0) for x0 in simp]
fun_val это значение функции? Если нет, нужно переименовать, чтобы отражало суть переменной

2024-04-16 12:56 UTC, DanilVolkov commented on method/nelder_mead.py
> +def ind_sec_max(arr):
Не понятно из названия, что делает функция. Лучше написать полное название функции, чтобы отражало суть.
Также с переменными.

2024-04-16 12:56 UTC, DanilVolkov commented on method/nelder_mead.py
> +    while not np.isclose(simp, simp[0]).all():
simp надо переименовать в полное имя переменной

2024-04-16 13:01 UTC, DanilVolkov commented
Сокращения в коде плохо читаются. Переменные нужно называть полными названиями. Кратко и ясно. Если все названия переменных сокращены, то такое ощущение, как будто читаешь книгу только с сокращениями слов.
Например:
`Жил.-был. дев. и баб. они оч. хот. ест.. Но прикл. несч. зак. ед.. Они стал. иск. ед., но не мог. найт.`

2024-04-16 14:54 UTC, StatsenkoArs commented on method/nelder_mead.py
> +        fun_val = [fun(x0) for x0 in simp]
именно оно и есть

2024-04-16 14:58 UTC, StatsenkoArs commented
ind, fun, dim может оставить, общепринятые все таки сокращения довольно длинных слов?

2024-04-16 15:22 UTC, DanilVolkov commented
> ind, fun, dim может оставить, общепринятые все таки сокращения довольно длинных слов?

Нет, будем писать даже длинные слова, чтобы было понятно. Сокращение слова может быть понятно одному человеку, но непонятно другому

2024-04-16 15:37 UTC, StatsenkoArs commented
Вроде все подправил, из того что ты говорил
С тестами стоит подождать парсер, мне кажется

2024-04-16 18:13 UTC, DanilVolkov approved these changes
Намного лучше читается)

2024-04-22 08:13 UTC, MariaBuznikova commented on method/nelder_mead.py
> +    return (sum(array) - array[exception_index]) / (len(array) - 1)
Создать переменную, которую будет возвращать функция. Чтоб строка не выглядела громоздко

2024-04-22 08:13 UTC, MariaBuznikova commented on method/nelder_mead.py
> +    return symmetrical_point(array_points, array_points[index_min], 0.5)
Аналогично можно создать отдельную переменную. Строки выглядят громоздко

2024-04-22 10:21 UTC, MariaBuznikova approved these changes

2024-04-22 10:22 UTC, merged